/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-20 05:24:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import main.java.reception.model.vo.Reception;
import main.java.common.model.vo.PageInfo;
import main.java.member.model.vo.Member;

public final class receptionBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/common/user-header1.jsp", Long.valueOf(1689818488790L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("main.java.common.model.vo.PageInfo");
    _jspx_imports_classes.add("main.java.reception.model.vo.Reception");
    _jspx_imports_classes.add("main.java.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	//String contextPath = request.getContextPath();

	// loginUser 세션에서 가져와야 함
	// loginUser에서 관리자인지 회원인지 구분 필요
	// Member loginUser = request.getSession().getAttribute("loginUser");
	ArrayList<Reception> list = (ArrayList<Reception>)request.getAttribute("list");
	// Reception r = (Reception)request.getAttribute("r");
	
	//String category = request.getParameter("category")==null?"선택":request.getParameter("category");
	String category = (String)request.getAttribute("category");
	// 값을 받아올 것이므로 이후 삭제 필요
	
	// 페이지 정보
	PageInfo pi = (PageInfo) request.getAttribute("pi");
	int currentPage = pi.getCurrentPage();
	int startPage   = pi.getStartPage();
	int endPage     = pi.getEndPage();
	int maxPage     = pi.getMaxPage(); 
	int pageLimit = pi.getPageLimit();
	
	String msg = (String)session.getAttribute("msg");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>My Reception</title>\n");
      out.write("\n");
      out.write("<!-- load css -->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/templatemo.css\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/customer-center.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!-- load fonts style -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/fontawesome.min.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!-- load script -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<!-- 헤더 페이지 추가 필요 -->\n");
      out.write("		");
      out.write('\r');
      out.write('\n');

	String contextPath = request.getContextPath();

	Member loginUser = (Member) session.getAttribute("loginUser");
	// 로그인전이라면 loginUser에는 null값이 담겨있을 것이고
	// 로그인성공 후라면, loginUser에는 로그인한 회원의 정보가 담긴 Member객체가 들어가 있을것.
    //로그인 한 사용자들이라면 userId에 값 담김
	if(loginUser!=null){
	   	String userId=loginUser.getUserId();
	}
   
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>header+footer</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/TimeForMaker/assets/img/TFM_icon.png\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/templatemo.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/user-header.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/admin-header.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/fontawesome.min.css\">\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<script>\r\n");
      out.write("		\r\n");
      out.write("		const msg = \"");
      out.print( (String)session.getAttribute("alertMsg") );
      out.write("\";\r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\"){\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			// 알림창을 띄워준 후 session에 담긴 해당 메세지는 지워줘야한다.\r\n");
      out.write("			// 안그럼, menubar.jsp가 로딩될때마다 항상 메세지가 뜰것..\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("   <!-- Header -->\r\n");
      out.write("   <nav class=\"navbar navbar-expand-lg navbar-light shadow main_nav_all admin_header\">\r\n");
      out.write("    <div class=\"container d-flex justify-content-between align-items-center\">\r\n");
      out.write("																			<!-- 여기에 메인페이지로 가는 길 -->\r\n");
      out.write("        <a class=\"navbar-brand text-success logo h1 align-self-center\" href=\"#\">\r\n");
      out.write("            <img src=\"/TimeForMaker/assets/img/메인로고.png\" class=\"main_logo\">\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler border-0\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#templatemo_main_nav\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between\" id=\"templatemo_main_nav\">\r\n");
      out.write("            <div class=\"flex-fill\">                \r\n");
      out.write("                 <ul class=\"nav justify-content-end\">\r\n");
      out.write("                 \r\n");
      out.write("                 	");
if(loginUser == null){//로그인 안했을때 실행부분
      out.write("\r\n");
      out.write("	                	<li class=\"nav-item\">\r\n");
      out.write("	                        <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/views/member/LoginMain.jsp\">로그인</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("	                    <li class=\"nav-item\">\r\n");
      out.write("	                        <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/views/member/SignUpCondition.jsp\">회원가입</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("	                     <li class=\"nav-item\">\r\n");
      out.write("	                        <a class=\"nav-link\" onclick=\"loginCheck();\" href=\"");
      out.print( contextPath );
      out.write("/views/mypage/MyPageEditInfo.jsp\" >고객센터</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("	                    \r\n");
      out.write("                    ");
}else{ //로그인했을때
      out.write("\r\n");
      out.write("	                    <li class=\"nav-item\">\r\n");
      out.write("	                        <a class=\"nav-link\" href=\"");
      out.print(contextPath );
      out.write("/Logout.me\">로그아웃</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("	                     <li class=\"nav-item\">\r\n");
      out.write("	                        <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/views/mypage/MyPageEditInfo.jsp\">고객센터</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("       				");
} 
      out.write("\r\n");
      out.write("                 </ul>                   \r\n");
      out.write("            </div>\r\n");
      out.write("       		\r\n");
      out.write("             <div class=\"navbar align-self-center d-flex login_check\">\r\n");
      out.write("             	<a class=\"nav-icon d-none d-lg-inline login_check\" href=\"#\">\r\n");
      out.write("			           <i class=\"fa fa-fw fa-search text-dark mr-2\"></i>\r\n");
      out.write("			      </a>\r\n");
      out.write("			      <a class=\"nav-icon position-relative text-decoration-none login_check\" href=\"");
      out.print( contextPath );
      out.write("/views/mypage/MyPageMain.jsp\" onclick=\"handleUserLink();\">\r\n");
      out.write("			           <i class=\"fa fa-fw fa-user text-dark mr-3\"></i>\r\n");
      out.write("	              </a>          \r\n");
      out.write("		     </div>\r\n");
      out.write("		      \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  		 	");
if(loginUser != null){//로그인 했을때 실행부분
      out.write("\r\n");
      out.write("				    ");
String managerType =loginUser.getManagerType(); 
      out.write("\r\n");
      out.write("	    			");
if(managerType.equals("M")){ 
      out.write("      			\r\n");
      out.write("				    	<div class=\" main_adminbar \">\r\n");
      out.write("				            <div class=\"main_admin_menu\">\r\n");
      out.write("				                <li class=\"main_admin_li\">\r\n");
      out.write("				                    <a class=\"main_admin_link\" href=\"");
      out.print( contextPath );
      out.write("/product.pd\">상품관리</a>\r\n");
      out.write("				                </li>\r\n");
      out.write("				                <li class=\"main_admin_li\">\r\n");
      out.write("				                    <a class=\"main_admin_link\" href=\"");
      out.print( contextPath );
      out.write("/reserve.rs\">예약관리</a>\r\n");
      out.write("				                </li>\r\n");
      out.write("				                <li class=\"main_admin_li\">\r\n");
      out.write("				                    <a class=\"main_admin_link\" href=\"");
      out.print(contextPath );
      out.write("/list.me\">회원관리</a>\r\n");
      out.write("				                </li>\r\n");
      out.write("				                <li class=\"main_admin_li\">\r\n");
      out.write("				                    <a class=\"main_admin_link\" href=\"");
      out.print( contextPath );
      out.write("/notice.nt\">고객센터관리</a>\r\n");
      out.write("				                </li>\r\n");
      out.write("				            </div>\r\n");
      out.write("				        </div>\r\n");
      out.write("				  ");
} 
      out.write("\r\n");
      out.write("			");
} 
      out.write("  \r\n");
      out.write("</nav>\r\n");
      out.write("	\r\n");
      out.write("<!-- Close Header -->\r\n");
      out.write("\r\n");
      out.write("       <script>\r\n");
      out.write("		   // 로그인 상태에 따라 클릭 가능한 링크와 알림 메시지를 처리하는 함수\r\n");
      out.write("		   function handleUserLink() {\r\n");
      out.write("		      ");
 if (loginUser != null) { 
      out.write("\r\n");
      out.write("		         // loginUser가 null이 아닌 경우, 링크 클릭 가능\r\n");
      out.write("		         const userLinks = document.getElementsByClassName(\"login_check\");\r\n");
      out.write("		         for (const i = 0; i < userLinks.length; i++) {\r\n");
      out.write("		            userLinks[i].href = \"#\";\r\n");
      out.write("		         }\r\n");
      out.write("		     ");
 } else { 
      out.write("\r\n");
      out.write("		         // loginUser가 null인 경우, 알림 메시지 표시\r\n");
      out.write("		         alert(\"로그인 후 사용 가능합니다.\");\r\n");
      out.write("		         \r\n");
      out.write("		     ");
 } 
      out.write("\r\n");
      out.write("		   }\r\n");
      out.write("		   \r\n");
      out.write("		   function loginCheck() {\r\n");
      out.write("		        alert(\"로그인 후 이용 가능합니다!\");\r\n");
      out.write("		    }\r\n");
      out.write("	</script>\r\n");
      out.write("       \r\n");
      out.write("    <!-- Start Script -->\r\n");
      out.write("    <script src=\"/TimeForMaker/assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <script src=\"/TimeForMaker/assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/TimeForMaker/assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"/TimeForMaker/assets/js/templatemo.js\"></script>\r\n");
      out.write("    <!-- End Script -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("	<!-- Close 헤더 파트 -->\n");
      out.write("\n");
      out.write("	<!-- Start 1:1 페이지 -->\n");
      out.write("    <div class=\"reception-side-container\" style=\"position: relative;\">\n");
      out.write("\n");
      out.write("        <!-- Start Side-Menu -->\n");
      out.write("        <div class=\"side-menu\">\n");
      out.write("            <ul class=\"list-group list-group-flush\">\n");
      out.write("                <li class=\"list-group-item list-group-title\"><span>고객센터</span></li>\n");
      out.write("                <li class=\"list-group-item list-group-sub\"><a href=\"");
      out.print(contextPath);
      out.write("/noticeBoard\">공지사항</a></li>\n");
      out.write("                <li class=\"list-group-item list-group-sub side-menu-selected\"><a href=\"");
      out.print(contextPath);
      out.write("/myReception\">1:1 문의</a></li>\n");
      out.write("              </ul>\n");
      out.write("        </div>\n");
      out.write("        <!-- Close Side-Menu -->\n");
      out.write("    \n");
      out.write("        <!-- Start Recept Board Container 문의내역 -->\n");
      out.write("        <div class=\"recept-part\"> \n");
      out.write("            <!-- Start Recept Page Title -->\n");
      out.write("            <h3 align=\"center\" class=\"customer-center-title\">1:1 문의</h3>\n");
      out.write("            <!-- Close Recept Page Title -->\n");
      out.write("\n");
      out.write("            <div class=\"recept-sub-menu\">\n");
      out.write("                <button class=\"recept-sub-menu-item recpet-sub-menu-selected\">문의 내역</butt>\n");
      out.write("                <button class=\"recept-sub-menu-item\">문의하기</button>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Start Recept Board Part -->\n");
      out.write("            <div class=\"recpet-part1\">\n");
      out.write("                \n");
      out.write("                <div class=\"recept-board-text\">\n");
      out.write("                    <h5>문의 서비스 관련 안내</h5>\n");
      out.write("                    <p>\n");
      out.write("                        회원님이&nbsp;7일간&nbsp;접수한&nbsp;문의&nbsp;내역을&nbsp;확인할&nbsp;수&nbsp;있습니다.<br>\n");
      out.write("                        해당&nbsp;기간&nbsp;이후에는&nbsp;본사에서&nbsp;데이터를&nbsp;파기하므로&nbsp;\n");
      out.write("                        회원님께선&nbsp;이전&nbsp;문의를&nbsp;확인하실&nbsp;수&nbsp;없습니다.<br>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <nav class=\"navbar navbar-expand-lg\" id=\"recept-search-bar\" style=\"background-color: transparent;\">\n");
      out.write("                    <!-- script단에서 요청 (-> /myReception 처리 필요) -->\n");
      out.write("                    <div class=\"container-fluid\">\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"navbarNavDarkDropdown\">\n");
      out.write("                            <ul class=\"navbar-nav\">\n");
      out.write("                                <li class=\"nav-item dropdown dropdown-center dropend\">\n");
      out.write("                                    <button class=\"nav-link dropdown-toggle\" type=\"button\" name=\"recept-category\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"border:0.8px solid black; background-color: transparent;\">\n");
      out.write("                                        <span>");
      out.print(category );
      out.write("</span>\n");
      out.write("                                    </button>\n");
      out.write("                                    <ul class=\"dropdown-menu dropdown-menu-middle\" id=\"recept-search-category-menu\" style=\"text-align: center; cursor:pointer\">\n");
      out.write("                                        <li class=\"dropdown-item\">전체</li>\n");
      out.write("                                        <li class=\"dropdown-item\">계정</li>\n");
      out.write("                                        <li class=\"dropdown-item\">예약</li>\n");
      out.write("                                        <li class=\"dropdown-item\">기타</li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("\n");
      out.write("                <!-- Start Recept Board Part -->\n");
      out.write("                <div class=\"container recept-board-area\" id=\"recept-board-area\">\n");
      out.write("                    <table class=\"table\" style=\"table-layout:fixed\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th scope=\"col\" width=\"10%\">No</th>\n");
      out.write("                                <th scope=\"col\" colspan=\"2\" width=\"60%\">문의 제목</th>\n");
      out.write("                                <th scope=\"col\" width=\"10%\">접수 일자</th>\n");
      out.write("                                <th scope=\"col\" width=\"10%\">처리상태</th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                        	");
 int i=0; 
      out.write("\n");
      out.write("                        	");
 if(list!=null){ 
      out.write("\n");
      out.write("                      			");
 for(Reception re : list){ 
      out.write("\n");
      out.write("	                        		<tr>\n");
      out.write("		                                <th scope=\"row\" height=\"40vh\">");
      out.print(re.getRowNum() );
      out.write("</th>\n");
      out.write("		                                <td colspan=\"2\"><a href=\"");
      out.print(contextPath);
      out.write("/myReceptionDetail?category=");
      out.print(category );
      out.write("&no=");
      out.print(re.getRowNum());
      out.write('"');
      out.write('>');
      out.print(re.getTitle() );
      out.write("</a></td>\n");
      out.write("		                                <td>");
      out.print(re.getUploadDate() );
      out.write("</td>\n");
      out.write("		                                <td>\n");
      out.write("		                                	");
 if(re.getStatus().equals("N")){ 
      out.write("\n");
      out.write("		                                		대기\n");
      out.write("		                                	");
 }else{ 
      out.write("\n");
      out.write("		                                		완료\n");
      out.write("		                                	");
 } 
      out.write("\n");
      out.write("		                                </td>\n");
      out.write("		                            </tr>\n");
      out.write("		                            ");
 i++; 
      out.write("\n");
      out.write("                      			");
 } 
      out.write("\n");
      out.write("                     		");
 } 
      out.write("\n");
      out.write("                        	");
 for(; i<5; i++){ 
      out.write(" \n");
      out.write("                       			<tr>\n");
      out.write("	                                <th height=\"40vh\"></th>\n");
      out.write("	                                <td colspan=\"2\"></td>\n");
      out.write("	                                <td></td>\n");
      out.write("	                                <td></td>\n");
      out.write("	                            </tr>\n");
      out.write("                        	");
 } 
      out.write("\n");
      out.write("                        </tbody>\n");
      out.write("                        <!-- <tfoot>\n");
      out.write("                        </tfoot> -->\n");
      out.write("                    </table>\n");
      out.write("        \n");
      out.write("                    <nav id=\"notice-recept-board-navi\" aria-label=\"Page navigation\">\n");
      out.write("		                <ul class=\"pagination justify-content-center\">\n");
      out.write("		                ");
 if(maxPage != pageLimit) { 
      out.write("\n");
      out.write("			                  <li class=\"page-item notice-page-pre\">\n");
      out.write("			                  	");
 if(startPage != 1){ 
      out.write("\n");
      out.write("			                  		<a class=\"page-link\" href=\"");
      out.print(contextPath);
      out.write("/myReception?page=");
      out.print(startPage-pageLimit);
      out.write("\" aria-label=\"Previous\">\n");
      out.write("				                    	<span aria-hidden=\"true\">&laquo;</span>\n");
      out.write("				                    </a>\n");
      out.write("			                    ");
 }else{ 
      out.write("\n");
      out.write("			                    	<a class=\"page-link\" aria-label=\"Previous\" onclick=\"return false;\">\n");
      out.write("				                    	<span aria-hidden=\"true\">&laquo;</span>\n");
      out.write("				                    </a>\n");
      out.write("			                    ");
 } 
      out.write("\n");
      out.write("			                      \n");
      out.write("			                  </li>\n");
      out.write("			              ");
 } 
      out.write("\n");
      out.write("			              \n");
      out.write("			              ");
 for(int p = startPage; p<= endPage; p++){ 
      out.write("\n");
      out.write("			              	");
 if(p==currentPage) { 
      out.write("\n");
      out.write("			                  <li class=\"page-item notice-recept-page-clicked\"><a class=\"page-link\" href=\"");
      out.print(contextPath);
      out.write("/myReception?page=");
      out.print(p );
      out.write("\" onclick=\"return false;\">");
      out.print(p );
      out.write("</a></li>\n");
      out.write("			              	");
 } else { 
      out.write("\n");
      out.write("			                  <li class=\"page-item\"><a class=\"page-link\" href=\"");
      out.print(contextPath);
      out.write("/myReception?page=");
      out.print(p );
      out.write('"');
      out.write('>');
      out.print(p );
      out.write("</a></li>	              	\n");
      out.write("			              	");
 } 
      out.write("\n");
      out.write("			              ");
 } 
      out.write("\n");
      out.write("		                  \n");
      out.write("		                  ");
 if(maxPage != pageLimit) { 
      out.write("\n");
      out.write("			                  <li class=\"page-item\">\n");
      out.write("			                  ");
 if(endPage == maxPage){ 
      out.write("\n");
      out.write("			                    <a class=\"page-link notice-page-next\" aria-label=\"Next\" onclick=\"return false;\">\n");
      out.write("			                      <span aria-hidden=\"true\">&raquo;</span>\n");
      out.write("			                    </a>\n");
      out.write("			                  ");
 } else{ 
      out.write("\n");
      out.write("			                  	<a class=\"page-link notice-page-next\" href=\"");
      out.print(contextPath);
      out.write("/myReception?page=");
      out.print(startPage+pageLimit);
      out.write("\" aria-label=\"Next\">\n");
      out.write("			                      <span aria-hidden=\"true\">&raquo;</span>\n");
      out.write("			                    </a>\n");
      out.write("			                  ");
 } 
      out.write("\n");
      out.write("			                  </li>\n");
      out.write("		                  ");
 } 
      out.write("\n");
      out.write("		                </ul>\n");
      out.write("		            </nav>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <!-- Close Recept Board Part -->\n");
      out.write("            \n");
      out.write("            <!-- Start Recept Entroll Form-->\n");
      out.write("            <div class=\"recept-part2\">\n");
      out.write("                <form class=\"recept-form\" action=\"uploadReception\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("                    <div class=\"mb-3 row\">\n");
      out.write("                        <input type=\"text\" hidden class=\"form-control-plaintext\" id=\"recept-form-category\" name=\"recept-form-category\" value=\"\">\n");
      out.write("\n");
      out.write("                        <label class=\"col-sm-2 col-form-label\">분류</label>\n");
      out.write("                        <div class=\"col-sm-7\">\n");
      out.write("                            <nav class=\"navbar navbar-expand-lg\" id=\"recept-form-bar\" style=\"background-color: transparent;\">\n");
      out.write("                                <!-- script단에서 요청 (-> /uploadReception 처리 필요) -->\n");
      out.write("                                <div class=\"container-fluid\">\n");
      out.write("                                    <div class=\"collapse navbar-collapse\" id=\"navbarNavDarkDropdown2\">\n");
      out.write("                                        <ul class=\"navbar-nav\">\n");
      out.write("                                            <li class=\"nav-item dropdown dropdown-center\">\n");
      out.write("                                                <button class=\"nav-link dropdown-toggle\" type=\"button\" id=\"recept-category-btn\" name=\"recept-category\" value=\"선택\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"border:0.8px solid black; background-color: transparent;\">\n");
      out.write("                                                    <span>선택</span>\n");
      out.write("                                                </button>\n");
      out.write("                                                <ul class=\"dropdown-menu dropdown-menu-middle\" id=\"recept-form-category-menu\" style=\"text-align: center; cursor:pointer\">\n");
      out.write("                                                    <li class=\"dropdown-item\">계정</li>\n");
      out.write("                                                    <li class=\"dropdown-item\">예약</li>\n");
      out.write("                                                    <li class=\"dropdown-item\">기타</li>\n");
      out.write("                                                </ul>\n");
      out.write("                                            </li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </nav>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3 row\">\n");
      out.write("                        <label class=\"col-sm-2 col-form-label\">제목</label>\n");
      out.write("                        <div class=\"col-sm-8\">\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"recept-form-title\" name=\"recept-form-title\" placeholder=\"제목을 입력해주세요\" required>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3 row\">\n");
      out.write("                        <label class=\"col-sm-2 col-form-label\">내용</label>\n");
      out.write("                        <div class=\"col-sm-8\">\n");
      out.write("                            <textarea class=\"form-control\" id=\"recept-form-content\" rows=\"13\" name=\"recept-form-content\" placeholder=\"내용을 입력해주세요\" onclick=\"this.select()\" onfocus=\"this.select()\" required></textarea>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3 row\">\n");
      out.write("                        <label class=\"col-sm-2 col-form-label\">파일첨부</label>\n");
      out.write("                        <div class=\"col-sm-8\">\n");
      out.write("                            <input type=\"file\" class=\"form-control\" id=\"recept-form-file\" name=\"recept-form-file\" accept=\"image/jpeg, image/png, .txt\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"mb-3 row recept-right-info-container\">\n");
      out.write("                        <label class=\"col-sm-2 col-form-label\">개인정보<br>수집 및 이용<br>동의</label>\n");
      out.write("                        <div class=\"col-sm-8\">\n");
      out.write("                            <span>문의 접수와 처리를 위한 최소한의 개인정보입니다. 동의를 필요로 합니다.</span>\n");
      out.write("                            <button type=\"button\" class=\"recept-right-info-btn\" id=\"recept-right-info-btn\">전문보기</button><br><br>\n");
      out.write("                            <input type=\"checkbox\" id=\"recept-form-agree\" name=\"recept-form-agree\"><label for=\"recept-form-agree\"><b>동의합니다</b></label>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"recept-right-info\">\n");
      out.write("                            <h2>개인정보 수집 및 이용동의 안내 (필수)</h2><br>\n");
      out.write("                            <p>[1:1 문의하기]를 이용하여 고객상담을 하는 경우 다음과 같은 개인정보를 수집하고 있습니다.</p>\n");
      out.write("                            <dl>\n");
      out.write("                                <dt>\n");
      out.write("                                    1&#41; 개인정보 수집 및 이용 목적\n");
      out.write("                                </dt>\n");
      out.write("                                <dd>서비스이용에 따른 본인확인, 문의하기 접수와 처리 및 결과 회신</dd>\n");
      out.write("                                \n");
      out.write("                                <dt>\n");
      out.write("                                    2&#41; 개인정보 수집항목\n");
      out.write("                                </dt>\n");
      out.write("                                <dd>필수 항목 : 이메일 주소</dd>\n");
      out.write("                                <dt>\n");
      out.write("                                    3&#41; 개인정보 보유 및 이용기간\n");
      out.write("                                </dt>\n");
      out.write("                                <dd>접수된 문의 처리 후 7일</dd>\n");
      out.write("                            </dl>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-warning recept-right-info-close\">닫기</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"submit\" onclick=\"return receptValidate()\">접수하기</button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Close Recept Entroll Form -->\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Close Recept Board Container -->\n");
      out.write("\n");
      out.write("        <!-- Start Recept Alert Box -->\n");
      out.write("        ");
 if(msg != null){ 
      out.write("\n");
      out.write("	        <div class=\"recept-alert-box\">\n");
      out.write("	            <button type=\"button\" class=\"btn btn-outline-dark recept-alert-box-close\">X</button>\n");
      out.write("	            <span>");
      out.print(msg );
      out.write("</span>\n");
      out.write("	        </div>\n");
      out.write("	       ");
 session.removeAttribute("msg"); 
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Close 1:1문의 페이지 -->\n");
      out.write("	\n");
      out.write("	 <!-- Start Footer -->\n");
      out.write("    <footer class=\"main_footer\" id=\"tempaltemo_footer\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("\n");
      out.write("                <div class=\"col-md-4 pt-5\">\n");
      out.write("                    <img src=\"");
      out.print(contextPath );
      out.write("/assets/img/메인로고.png\" class=\"main_logo\">\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\n");
      out.write("                        <li>\n");
      out.write("                            <i class=\"fas fa-map-marker-alt fa-fw\"></i>\n");
      out.write("                            서울특별시 강남구 테헤란로14길6\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <i class=\"fa fa-phone fa-fw\"></i>\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <i class=\"fa fa-envelope fa-fw\"></i>\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"mailto:info@company.com\">info@company.com</a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"w-100 py-3\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row pt-2\">\n");
      out.write("                    <div class=\"col-12\">\n");
      out.write("                        <p class=\"text-left\">\n");
      out.write("                            &copy; 2023 떡잎방범대 박수진 박지현 이아인 임재린 황슬기\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </footer>\n");
      out.write("    <!-- End Footer -->\n");
      out.write("	\n");
      out.write("	<!-- Start Script -->\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/assets/js/templatemo.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/assets/js/customer-center.js\"></script>\n");
      out.write("    <script>\n");
      out.write("	    /* 문의 유형 선택 이벤트 */\n");
      out.write("	    $(\"#recept-search-category-menu>li\").click(function(){\n");
      out.write("	        let value=$(this).text();\n");
      out.write("	        $(\"#recept-search-bar button span\").text(value);\n");
      out.write("	\n");
      out.write("	        let url='myReception?category='+value;\n");
      out.write("	        location.href=url;\n");
      out.write("	    });\n");
      out.write("	\n");
      out.write("	    $(\"#recept-form-category-menu>li\").click(function(){\n");
      out.write("	        let value=$(this).text();\n");
      out.write("	\n");
      out.write("	        $(\"#navbarNavDarkDropdown2 button span\").text(value);\n");
      out.write("	        $(\"#recept-form-category\").val(value);\n");
      out.write("	    });\n");
      out.write("	\n");
      out.write("	    /* 공지사항 게시판 페이징 버튼 효과 */\n");
      out.write("	    $(\".page-item\").click(function(){\n");
      out.write("	        $(this).siblings().removeClass(\"notice-recept-page-clicked\");\n");
      out.write("	        $(this).addClass(\"notice-recept-page-clicked\"); \n");
      out.write("	        console.log(this.classList);\n");
      out.write("	    });\n");
      out.write("	\n");
      out.write("	    /* 게시판에 빈 라인 hover삭제 */\n");
      out.write("	    $(\"#recept-board-area tbody tr\").hover(function(){\n");
      out.write("	        if($(this).children(\"th\").text()!=\"\"){\n");
      out.write("	            $(this).css(\"background-color\",\"#F7F0D4\");\n");
      out.write("	        }\n");
      out.write("	    }, function(){\n");
      out.write("	        $(this).css(\"background-color\",\"transparent\");\n");
      out.write("	    });\n");
      out.write("	\n");
      out.write("	    /* 게시판 빈칸 속성지정 */\n");
      out.write("	    $(\"#recept-board-area tbody tr>th\").each(function(index){\n");
      out.write("	        if($(this).text()==\"\"){\n");
      out.write("	            $(\"#recept-board-area tbody tr\").eq(index).css(\"border\",\"white\");\n");
      out.write("	            if(index==4){\n");
      out.write("	                $(\"#recept-board-area tbody tr\").eq(index).css(\"border-bottom\",\"black\");\n");
      out.write("	            }\n");
      out.write("	        }else{\n");
      out.write("	        	if(index==4){\n");
      out.write("	                $(\"#recept-board-area tbody tr\").eq(index).css(\"border-bottom\",\"black\");\n");
      out.write("	            }\n");
      out.write("	        }\n");
      out.write("	    });\n");
      out.write("	\n");
      out.write("	    /* 하위 메뉴 클릭시 속성 */\n");
      out.write("	    $(\".recept-sub-menu-item\").click(function(){\n");
      out.write("	        $(this).siblings().removeClass(\"recpet-sub-menu-selected\");\n");
      out.write("	        $(this).addClass(\"recpet-sub-menu-selected\");\n");
      out.write("	        // console.log($(this).index());\n");
      out.write("	\n");
      out.write("	        if($(this).index()==0){\n");
      out.write("	            $(\".recpet-part1\").css(\"display\",\"block\");\n");
      out.write("	            $(\".recept-part2\").css(\"display\",\"none\");\n");
      out.write("	        }else{\n");
      out.write("	            $(\".recpet-part1\").css(\"display\",\"none\");\n");
      out.write("	            $(\".recept-part2\").css(\"display\",\"block\");\n");
      out.write("	        }\n");
      out.write("	    });\n");
      out.write("	\n");
      out.write("	    /* 문의폼 작성 */ \n");
      out.write("	    function receptValidate(){\n");
      out.write("	    	if($(\"#recept-category-btn>span\").text()==\"선택\"){\n");
      out.write("                $(\"#recept-category-btn\").css(\"border\",\"1px solid red\");\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            if(!$(\"#recept-form-agree\").is(\":checked\")){\n");
      out.write("                $(\"#recept-form-agree\").css({\n");
      out.write("                	\"outline-style\": \"solid\", \"outline-color\" : \"red\", \"outline-width\" : \"2px\"\n");
      out.write("                });\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("            return true;\n");
      out.write("        }\n");
      out.write("	    \n");
      out.write("	    /* 폼체크 표시 해제 이벤트 */\n");
      out.write("	    $(\"#recept-form-category-menu>li, #recept-form-agree\").click(()=>{\n");
      out.write("            if(document.getElementById(\"recept-category-btn\").style.border == \"1px solid red\"){\n");
      out.write("                document.getElementById(\"recept-category-btn\").style.border = \"1px solid black\";\n");
      out.write("            }\n");
      out.write("            if(document.getElementById(\"recept-form-agree\").style.outlineStyle==\"solid\"){\n");
      out.write("                document.getElementById(\"recept-form-agree\").style.outlineStyle=\"none\";\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("	\n");
      out.write("	    /* 개인정보수집동의안내 전문보기 */\n");
      out.write("	    $(\"#recept-right-info-btn\").click(function(){\n");
      out.write("	        $(\".recept-right-info\").css(\"display\",\"block\");\n");
      out.write("	    });\n");
      out.write("	\n");
      out.write("	    $(\".recept-right-info-close\").click(()=>{$(\".recept-right-info\").css(\"display\",\"none\");});\n");
      out.write("	\n");
      out.write("	    /* 문의접수 알림창 --배경색 에러 */\n");
      out.write("	    $(\".recept-alert-box-close\").click(()=>{\n");
      out.write("	        $(this).css(\"background-color\",\"red\");\n");
      out.write("	        $(\".recept-alert-box\").css(\"display\",\"none\");\n");
      out.write("		});\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("    <!-- End Script -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
