/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-20 02:27:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import main.java.member.model.vo.Member;
import main.java.product.model.vo.Product;
import java.util.ArrayList;
import main.java.member.model.vo.UserKeyword;
import main.java.member.model.vo.Member;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/common/user-header1.jsp", Long.valueOf(1689818488790L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("main.java.product.model.vo.Product");
    _jspx_imports_classes.add("main.java.member.model.vo.UserKeyword");
    _jspx_imports_classes.add("main.java.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>TFM_main</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"icon\"\r\n");
      out.write("	href=\"/TimeForMaker/img/TFM_icon.png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/templatemo.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/TimeForMaker/assets/css/fontawesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 메인에서 지역, 추천 슬라이드 바 만드는 슬릭 링크 시작 (황슬기 추가)-->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/TimeForMaker/assets/css/slick.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/TimeForMaker/assets/css/slick-theme.css\">\r\n");
      out.write("\r\n");
      out.write("<!--슬릭 링크 끝(슬기)-->\r\n");
      out.write("<!--메인 css링크 (슬기) 위에 슬릭 링크 뒤에 있어야 마지막 버튼 스타일이 먹힘..!-->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/main.css\">\r\n");
      out.write("<!--이건 메인 바디부분 css-->\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

	String contextPath = request.getContextPath();

	Member loginUser = (Member) session.getAttribute("loginUser");
	// 로그인전이라면 loginUser에는 null값이 담겨있을 것이고
	// 로그인성공 후라면, loginUser에는 로그인한 회원의 정보가 담긴 Member객체가 들어가 있을것.
    //로그인 한 사용자들이라면 userId에 값 담김
	if(loginUser!=null){
	   	String userId=loginUser.getUserId();
	}
   
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>header+footer</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/TimeForMaker/assets/img/TFM_icon.png\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/templatemo.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/user-header.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/admin-header.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/TimeForMaker/assets/css/fontawesome.min.css\">\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<script>\r\n");
      out.write("		\r\n");
      out.write("		const msg = \"");
      out.print( (String)session.getAttribute("alertMsg") );
      out.write("\";\r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\"){\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			// 알림창을 띄워준 후 session에 담긴 해당 메세지는 지워줘야한다.\r\n");
      out.write("			// 안그럼, menubar.jsp가 로딩될때마다 항상 메세지가 뜰것..\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("   <!-- Header -->\r\n");
      out.write("   <nav class=\"navbar navbar-expand-lg navbar-light shadow main_nav_all admin_header\">\r\n");
      out.write("    <div class=\"container d-flex justify-content-between align-items-center\">\r\n");
      out.write("																			<!-- 여기에 메인페이지로 가는 길 -->\r\n");
      out.write("        <a class=\"navbar-brand text-success logo h1 align-self-center\" href=\"#\">\r\n");
      out.write("            <img src=\"/TimeForMaker/assets/img/메인로고.png\" class=\"main_logo\">\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler border-0\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#templatemo_main_nav\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between\" id=\"templatemo_main_nav\">\r\n");
      out.write("            <div class=\"flex-fill\">                \r\n");
      out.write("                 <ul class=\"nav justify-content-end\">\r\n");
      out.write("                 \r\n");
      out.write("                 	");
if(loginUser == null){//로그인 안했을때 실행부분
      out.write("\r\n");
      out.write("	                	<li class=\"nav-item\">\r\n");
      out.write("	                        <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/views/member/LoginMain.jsp\">로그인</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("	                    <li class=\"nav-item\">\r\n");
      out.write("	                        <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/views/member/SignUpCondition.jsp\">회원가입</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("	                     <li class=\"nav-item\">\r\n");
      out.write("	                        <a class=\"nav-link\" onclick=\"loginCheck();\" href=\"");
      out.print( contextPath );
      out.write("/views/mypage/MyPageEditInfo.jsp\" >고객센터</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("	                    \r\n");
      out.write("                    ");
}else{ //로그인했을때
      out.write("\r\n");
      out.write("	                    <li class=\"nav-item\">\r\n");
      out.write("	                        <a class=\"nav-link\" href=\"");
      out.print(contextPath );
      out.write("/Logout.me\">로그아웃</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("	                     <li class=\"nav-item\">\r\n");
      out.write("	                        <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/views/mypage/MyPageEditInfo.jsp\">고객센터</a>\r\n");
      out.write("	                    </li>\r\n");
      out.write("       				");
} 
      out.write("\r\n");
      out.write("                 </ul>                   \r\n");
      out.write("            </div>\r\n");
      out.write("       		\r\n");
      out.write("             <div class=\"navbar align-self-center d-flex login_check\">\r\n");
      out.write("             	<a class=\"nav-icon d-none d-lg-inline login_check\" href=\"#\">\r\n");
      out.write("			           <i class=\"fa fa-fw fa-search text-dark mr-2\"></i>\r\n");
      out.write("			      </a>\r\n");
      out.write("			      <a class=\"nav-icon position-relative text-decoration-none login_check\" href=\"");
      out.print( contextPath );
      out.write("/views/mypage/MyPageMain.jsp\" onclick=\"handleUserLink();\">\r\n");
      out.write("			           <i class=\"fa fa-fw fa-user text-dark mr-3\"></i>\r\n");
      out.write("	              </a>          \r\n");
      out.write("		     </div>\r\n");
      out.write("		      \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  		 	");
if(loginUser != null){//로그인 했을때 실행부분
      out.write("\r\n");
      out.write("				    ");
String managerType =loginUser.getManagerType(); 
      out.write("\r\n");
      out.write("	    			");
if(managerType.equals("M")){ 
      out.write("      			\r\n");
      out.write("				    	<div class=\" main_adminbar \">\r\n");
      out.write("				            <div class=\"main_admin_menu\">\r\n");
      out.write("				                <li class=\"main_admin_li\">\r\n");
      out.write("				                    <a class=\"main_admin_link\" href=\"");
      out.print( contextPath );
      out.write("/product.pd\">상품관리</a>\r\n");
      out.write("				                </li>\r\n");
      out.write("				                <li class=\"main_admin_li\">\r\n");
      out.write("				                    <a class=\"main_admin_link\" href=\"");
      out.print( contextPath );
      out.write("/reserve.rs\">예약관리</a>\r\n");
      out.write("				                </li>\r\n");
      out.write("				                <li class=\"main_admin_li\">\r\n");
      out.write("				                    <a class=\"main_admin_link\" href=\"");
      out.print(contextPath );
      out.write("/list.me\">회원관리</a>\r\n");
      out.write("				                </li>\r\n");
      out.write("				                <li class=\"main_admin_li\">\r\n");
      out.write("				                    <a class=\"main_admin_link\" href=\"");
      out.print( contextPath );
      out.write("/notice.nt\">고객센터관리</a>\r\n");
      out.write("				                </li>\r\n");
      out.write("				            </div>\r\n");
      out.write("				        </div>\r\n");
      out.write("				  ");
} 
      out.write("\r\n");
      out.write("			");
} 
      out.write("  \r\n");
      out.write("</nav>\r\n");
      out.write("	\r\n");
      out.write("<!-- Close Header -->\r\n");
      out.write("\r\n");
      out.write("       <script>\r\n");
      out.write("		   // 로그인 상태에 따라 클릭 가능한 링크와 알림 메시지를 처리하는 함수\r\n");
      out.write("		   function handleUserLink() {\r\n");
      out.write("		      ");
 if (loginUser != null) { 
      out.write("\r\n");
      out.write("		         // loginUser가 null이 아닌 경우, 링크 클릭 가능\r\n");
      out.write("		         const userLinks = document.getElementsByClassName(\"login_check\");\r\n");
      out.write("		         for (const i = 0; i < userLinks.length; i++) {\r\n");
      out.write("		            userLinks[i].href = \"#\";\r\n");
      out.write("		         }\r\n");
      out.write("		     ");
 } else { 
      out.write("\r\n");
      out.write("		         // loginUser가 null인 경우, 알림 메시지 표시\r\n");
      out.write("		         alert(\"로그인 후 사용 가능합니다.\");\r\n");
      out.write("		         \r\n");
      out.write("		     ");
 } 
      out.write("\r\n");
      out.write("		   }\r\n");
      out.write("		   \r\n");
      out.write("		   function loginCheck() {\r\n");
      out.write("		        alert(\"로그인 후 이용 가능합니다!\");\r\n");
      out.write("		    }\r\n");
      out.write("	</script>\r\n");
      out.write("       \r\n");
      out.write("    <!-- Start Script -->\r\n");
      out.write("    <script src=\"/TimeForMaker/assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <script src=\"/TimeForMaker/assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/TimeForMaker/assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"/TimeForMaker/assets/js/templatemo.js\"></script>\r\n");
      out.write("    <!-- End Script -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		String userId=null;
			if(loginUser!=null){
			   	userId =loginUser.getUserId();	
			}
			System.out.println("userid: " + userId);

		ArrayList<UserKeyword> recomlist = (ArrayList<UserKeyword>) session.getAttribute("recomlist");
		System.out.println("recomlist: " + recomlist);
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Banner Hero -->\r\n");
      out.write("	<div id=\"template-mo-zay-hero-carousel\" class=\"carousel slide\"\r\n");
      out.write("		data-bs-ride=\"carousel\">\r\n");
      out.write("		<ol class=\"carousel-indicators\">\r\n");
      out.write("			<li data-bs-target=\"#template-mo-zay-hero-carousel\"\r\n");
      out.write("				data-bs-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("			<li data-bs-target=\"#template-mo-zay-hero-carousel\"\r\n");
      out.write("				data-bs-slide-to=\"1\"></li>\r\n");
      out.write("			<li data-bs-target=\"#template-mo-zay-hero-carousel\"\r\n");
      out.write("				data-bs-slide-to=\"2\"></li>\r\n");
      out.write("			<li data-bs-target=\"#template-mo-zay-hero-carousel\"\r\n");
      out.write("				data-bs-slide-to=\"3\"></li>\r\n");
      out.write("		</ol>\r\n");
      out.write("		<div class=\"carousel-inner\">\r\n");
      out.write("			<div class=\"carousel-item active\">\r\n");
      out.write("				<div class=\"main_banner\">\r\n");
      out.write("					<div class=\"row p-5\">\r\n");
      out.write("						<div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("							<a href=\"#\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/TimeForMaker/assets/img/찐메인배너1.png\"\r\n");
      out.write("								alt=\"\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<div class=\"main_banner\">\r\n");
      out.write("					<div class=\"row p-5\">\r\n");
      out.write("						<div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("							<a href=\"");
      out.print(contextPath );
      out.write("/banner.ma?ban=음식\"> \r\n");
      out.write("							<img class=\"img-fluid\"	src=\"/TimeForMaker/assets/img/찐메인배너2.png\" alt=\"\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<div class=\"main_banner\">\r\n");
      out.write("					<div class=\"row p-5\">\r\n");
      out.write("						<div class=\"mx-auto col-md-8 col-lg-6 align-items-center\">\r\n");
      out.write("						<a href=\"");
      out.print(contextPath );
      out.write("/banner.ma?ban=반려동물\">						\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/TimeForMaker/assets/img/찐메인배너3.png\" alt=\"\">\r\n");
      out.write("						</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-item\">\r\n");
      out.write("				<div class=\"main_banner\">\r\n");
      out.write("					<div class=\"row p-5\">\r\n");
      out.write("						<div class=\"mx-auto col-md-8 col-lg-6 align-items-center\">\r\n");
      out.write("						<a href=\"");
      out.print(contextPath );
      out.write("/banner.ma?ban=플라워\">\r\n");
      out.write("							<img class=\"img-fluid\" src=\"/TimeForMaker/assets/img/찐메인배너4.png\"\r\n");
      out.write("								alt=\"\">\r\n");
      out.write("						</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<a class=\"carousel-control-prev text-decoration-none w-auto ps-3\"\r\n");
      out.write("			href=\"#template-mo-zay-hero-carousel\" role=\"button\"\r\n");
      out.write("			data-bs-slide=\"prev\"> <i class=\"fas fa-chevron-left\"></i>\r\n");
      out.write("		</a> <a class=\"carousel-control-next text-decoration-none w-auto pe-3\"\r\n");
      out.write("			href=\"#template-mo-zay-hero-carousel\" role=\"button\"\r\n");
      out.write("			data-bs-slide=\"next\"> <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("		</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Banner Hero -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"main_all\">\r\n");
      out.write("		<!-- 배너 뒤로 이어지는 부분-->\r\n");
      out.write("		<!-- 여기서부터 지역별  -->\r\n");
      out.write("		<section class=\"container py-5\">\r\n");
      out.write("			<div class=\"main_loca\">\r\n");
      out.write("				<div class=\"main_loca_title\">\r\n");
      out.write("					<h4>어느 지역을 찾으시나요?</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"main_loca_item_bar\">\r\n");
      out.write("					<div class=\"main_loca_item\">\r\n");
      out.write("						<a href=\"");
      out.print(contextPath );
      out.write("/locasearch.ma?clo=강남구\"\r\n");
      out.write("							style=\"background-image: url(&quot;https://d21sjc85fy47a6.cloudfront.net/aaaaaqx/md/0706apgujeong.jpg?small200&quot;);\">\r\n");
      out.write("							<span class=\"label\">강남구</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_loca_item\">\r\n");
      out.write("						<a href=\"");
      out.print(contextPath );
      out.write("/locasearch.ma?clo=용산구\"\r\n");
      out.write("							style=\"background-image: url(&quot;https://d21sjc85fy47a6.cloudfront.net/aaaaaqx/md/0706itaewon.jpg?small200&quot;);\">\r\n");
      out.write("							<span class=\"label\">용산구</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_loca_item\">\r\n");
      out.write("						<a href=\"");
      out.print(contextPath );
      out.write("/locasearch.ma?clo=성동구\"\r\n");
      out.write("							style=\"background-image: url(&quot;https://d21sjc85fy47a6.cloudfront.net/aaaaaqx/md/0706sungsoo.jpg?small200&quot;);\">\r\n");
      out.write("							<span class=\"label\">성동구</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_loca_item\">\r\n");
      out.write("						<a href=\"");
      out.print(contextPath );
      out.write("/locasearch.ma?clo=종로구\"\r\n");
      out.write("							style=\"background-image: url(&quot;https://d21sjc85fy47a6.cloudfront.net/aaaaaqx/md/0706gwanghwamun.jpg?small200&quot;);\">\r\n");
      out.write("							<span class=\"label\">종로구</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_loca_item\">\r\n");
      out.write("						<a href=\"");
      out.print(contextPath );
      out.write("/locasearch.ma?clo=중구\"\r\n");
      out.write("							style=\"background-image: url(&quot;https://d21sjc85fy47a6.cloudfront.net/aaaaaqx/md/0706euljiro_0331.jpg?small200&quot;);\">\r\n");
      out.write("							<span class=\"label\">중구</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_loca_item\">\r\n");
      out.write("						<a href=\"");
      out.print(contextPath );
      out.write("/locasearch.ma?clo=마포구\"\r\n");
      out.write("							style=\"background-image: url(&quot;https://d21sjc85fy47a6.cloudfront.net/aaaaaqx/md_2022/0609_location_hapjeong,mangwon.png?small200&quot;);\">\r\n");
      out.write("							<span class=\"label\">마포구</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_loca_item\">\r\n");
      out.write("						<a href=\"");
      out.print(contextPath );
      out.write("/locasearch.ma?clo=관악구\"\r\n");
      out.write("							style=\"background-image: url(&quot;https://d21sjc85fy47a6.cloudfront.net/aaaaaqx/md/0706hongdae.jpg?small200&quot;);\">\r\n");
      out.write("							<span class=\"label\">관악구</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_loca_item\">\r\n");
      out.write("						<a href=\"");
      out.print(contextPath );
      out.write("/locasearch.ma?clo=영등포구\"\r\n");
      out.write("							style=\"background-image: url(&quot;https://d21sjc85fy47a6.cloudfront.net/aaaaaqx/md/0706yeouido.jpg?small200&quot;);\">\r\n");
      out.write("							<span class=\"label\">영등포구</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- 지역별 끝 -->\r\n");
      out.write("\r\n");
      out.write("		<!-- 추천 하드코딩^^ ㅛ -->\r\n");
      out.write("		<section class=\"container py-5\">\r\n");
      out.write("			<div class=\"main_recom\">\r\n");
      out.write("				<div class=\"main_recom_title\">\r\n");
      out.write("					<h4>이런 클래스는 어떠세요?</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"main_recom_item_bar\">\r\n");
      out.write("					<div class=\"main_recom_item_wap\">\r\n");
      out.write("						<a href=\"\"> <!-- 여기로 경로 표시 -->\r\n");
      out.write("							<div class=\"main_recom_item_img\">\r\n");
      out.write("								<img class=\"card-img rounded-0 img-fluid\"\r\n");
      out.write("									src=\"/TimeForMaker/assets/img/classimg/c_9_1.JPG\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"main_recom_item_body\">\r\n");
      out.write("								<br> <a class=\"main_class_name\">클래스이름111</a>\r\n");
      out.write("								<ul class=\"main_class_key\">\r\n");
      out.write("									<li>키워드</li>\r\n");
      out.write("									<li>위치키워드</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<p class=\"main_class_price\">50,000₩</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_recom_item_wap \">\r\n");
      out.write("						<a href=\"\">\r\n");
      out.write("							<div class=\"main_recom_item_img\">\r\n");
      out.write("								<img class=\"card-img rounded-0 img-fluid\"\r\n");
      out.write("									src=\"/TimeForMaker/assets/img/classimg/c_9_1.JPG\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"main_recom_item_body\">\r\n");
      out.write("								<br> <a class=\"main_class_name\">클래스이름111</a>\r\n");
      out.write("								<ul class=\"main_class_key\">\r\n");
      out.write("									<li>키워드</li>\r\n");
      out.write("									<li>위치키워드</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<p class=\"main_class_price\">50,000₩</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_recom_item_wap \">\r\n");
      out.write("						<a href=\"\">\r\n");
      out.write("							<div class=\"main_recom_item_img\">\r\n");
      out.write("								<img class=\"card-img rounded-0 img-fluid\"\r\n");
      out.write("									src=\"/TimeForMaker/assets/img/classimg/c_9_1.JPG\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"main_recom_item_body\">\r\n");
      out.write("								<br> <a class=\"main_class_name\">클래스이름111</a>\r\n");
      out.write("								<ul class=\"main_class_key\">\r\n");
      out.write("									<li>키워드</li>\r\n");
      out.write("									<li>위치키워드</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<p class=\"main_class_price\">50,000₩</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_recom_item_wap \">\r\n");
      out.write("						<a href=\"\">\r\n");
      out.write("							<div class=\"main_recom_item_img\">\r\n");
      out.write("								<img class=\"card-img rounded-0 img-fluid\"\r\n");
      out.write("									src=\"/TimeForMaker/assets/img/classimg/c_9_1.JPG\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"main_recom_item_body\">\r\n");
      out.write("								<br> <a class=\"main_class_name\">클래스이름111</a>\r\n");
      out.write("								<ul class=\"main_class_key\">\r\n");
      out.write("									<li>키워드</li>\r\n");
      out.write("									<li>위치키워드</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<p class=\"main_class_price\">50,000₩</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main_recom_item_wap \">\r\n");
      out.write("						<a href=\"\">\r\n");
      out.write("							<div class=\"main_recom_item_img\">\r\n");
      out.write("								<img class=\"card-img rounded-0 img-fluid\"\r\n");
      out.write("									src=\"/TimeForMaker/assets/img/classimg/c_9_1.JPG\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"main_recom_item_body\">\r\n");
      out.write("								<br> <a class=\"main_class_name\">클래스이름111</a>\r\n");
      out.write("								<ul class=\"main_class_key\">\r\n");
      out.write("									<li>키워드</li>\r\n");
      out.write("									<li>위치키워드</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<p class=\"main_class_price\">50,000₩</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- 키워드추천(로그인, 키워드 입력 고객만 보임 -->\r\n");
      out.write("		\r\n");
      out.write("		");
 if(userId != null){ 
      out.write("\r\n");
      out.write("		");
 if(recomlist != null && !recomlist.isEmpty()){ 
      out.write("\r\n");
      out.write("		<section class=\"container py-5\">		\r\n");
      out.write("			<div class=\"main_recom\">\r\n");
      out.write("				<div class=\"main_recom_title\">\r\n");
      out.write("					<h4>고객님만을 위한 추천 클래스~!</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"main_recom_item_bar\">	\r\n");
      out.write("					");
for (UserKeyword uk : recomlist) {
      out.write("\r\n");
      out.write("					\r\n");
      out.write("						<div class=\"main_recom_item_wap\">\r\n");
      out.write("							<div class=\"main_recom_item_img\">\r\n");
      out.write("								<a href=\"\"> <img class=\"card-img rounded-0 img-fluid\"\r\n");
      out.write("									src=\"/TimeForMaker/assets/img/classimg/c_9_1.JPG\">\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"main_recom_item_body\">\r\n");
      out.write("								<br> <a class=\"main_class_name\">");
      out.print(uk.getClassName());
      out.write("</a>\r\n");
      out.write("								<ul class=\"main_class_key\">\r\n");
      out.write("									<li>");
      out.print(uk.getClassCategory() );
      out.write("</li>\r\n");
      out.write("									<li>");
      out.print(uk.getClassKeyword() );
      out.write("</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<p class=\"main_class_price\">");
      out.print(uk.getPrice());
      out.write("₩</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("							");
} 
      out.write("				\r\n");
      out.write("					");
 }else{ session.removeAttribute("recomlist");//키워드 안하면 세션에서 지워줌
      out.write("\r\n");
      out.write("					");
  } 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>			\r\n");
      out.write("		</section>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("		<div class=\"main_allclass_btnarea\">\r\n");
      out.write("			<button class=\"main_allbtn\"\r\n");
      out.write("				onclick=\"window.location.href='");
      out.print(contextPath);
      out.write("/views/product/productList.jsp'\">\r\n");
      out.write("				더많은 클래스 보기</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 추천끝 -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Footer -->\r\n");
      out.write("	<footer class=\"main_footer\" id=\"tempaltemo_footer\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-4 pt-5\">\r\n");
      out.write("					<img src=\"/TimeForMaker/assets/img/메인로고.png\" class=\"main_logo\">\r\n");
      out.write("					<ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("						<li><i class=\"fas fa-map-marker-alt fa-fw\"></i> 서울특별시 강남구\r\n");
      out.write("							테헤란로14길6</li>\r\n");
      out.write("						<li><i class=\"fa fa-phone fa-fw\"></i> <a\r\n");
      out.write("							class=\"text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><i class=\"fa fa-envelope fa-fw\"></i> <a\r\n");
      out.write("							class=\"text-decoration-none\" href=\"mailto:info@company.com\">info@company.com</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"w-100 py-3\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row pt-2\">\r\n");
      out.write("					<div class=\"col-12\">\r\n");
      out.write("						<p class=\"text-left\">&copy; 2023 떡잎방범대 박수진 박지현 이아인 임재린 황슬기</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Script -->\r\n");
      out.write("	<script src=\"/TimeForMaker/assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("	<script src=\"/TimeForMaker/assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"/TimeForMaker/assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"/TimeForMaker/assets/js/templatemo.js\"></script>\r\n");
      out.write("	<!-- End Script -->\r\n");
      out.write("\r\n");
      out.write("	<!-- 메인 지역별, 추천별 슬라이드 스크립트 시작(슬기)-->\r\n");
      out.write("	<script src=\"/TimeForMaker/assets/js/slick.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("       //이건 지역별\r\n");
      out.write("       $('.main_loca_item_bar').slick({\r\n");
      out.write("            lazyLoad: 'ondemand',\r\n");
      out.write("            slidesToShow: 6,\r\n");
      out.write("            slidesToScroll: 1,\r\n");
      out.write("            prevArrow : '<i class=\"fas fa-chevron-left\" style=\"visibility: hidden;\"></i>',\r\n");
      out.write("		    nextArrow : '<i class=\"fas fa-chevron-right\"></i>',\r\n");
      out.write("            responsive: [{\r\n");
      out.write("                    breakpoint: 1024,\r\n");
      out.write("                    settings: {\r\n");
      out.write("                        slidesToShow: 3,\r\n");
      out.write("                        slidesToScroll: 2\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    breakpoint: 600,\r\n");
      out.write("                    settings: {\r\n");
      out.write("                        slidesToShow: 2,\r\n");
      out.write("                        slidesToScroll: 1\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    breakpoint: 480,\r\n");
      out.write("                    settings: {\r\n");
      out.write("                        slidesToShow: 2,\r\n");
      out.write("                        slidesToScroll: 1\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            ]\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("       //이건 추천별\r\n");
      out.write("\r\n");
      out.write("       $(function(){\r\n");
      out.write("			$('.main_recom_item_bar').slick({\r\n");
      out.write("				slide: 'div',		//슬라이드 되어야 할 태그 ex) div, li \r\n");
      out.write("				infinite : true, 	//무한 반복 옵션	 \r\n");
      out.write("				slidesToShow : 4,		// 한 화면에 보여질 컨텐츠 개수\r\n");
      out.write("				slidesToScroll : 1,		//스크롤 한번에 움직일 컨텐츠 개수\r\n");
      out.write("				speed : 100,	 // 다음 버튼 누르고 다음 화면 뜨는데까지 걸리는 시간(ms)\r\n");
      out.write("				arrows : true, 		// 옆으로 이동하는 화살표 표시 여부\r\n");
      out.write("				autoplay : true,			// 자동 스크롤 사용 여부\r\n");
      out.write("				autoplaySpeed : 5000, 		// 자동 스크롤 시 다음으로 넘어가는데 걸리는 시간 (ms)\r\n");
      out.write("				pauseOnHover : true,		// 슬라이드 이동	시 마우스 호버하면 슬라이더 멈추게 설정\r\n");
      out.write("				prevArrow : '<i class=\"fas fa-chevron-left\"></i>',		// 이전 화살표 모양 설정\r\n");
      out.write("				nextArrow : '<i class=\"fas fa-chevron-right\"></i>',		// 다음 화살표 모양 설정\r\n");
      out.write("				draggable : true, 	//드래그 가능 여부 \r\n");
      out.write("				\r\n");
      out.write("				responsive: [{\r\n");
      out.write("                        breakpoint: 1024,\r\n");
      out.write("                        settings: {\r\n");
      out.write("                            slidesToShow: 3,\r\n");
      out.write("                            slidesToScroll: 1\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        breakpoint: 600,\r\n");
      out.write("                        settings: {\r\n");
      out.write("                            slidesToShow: 2,\r\n");
      out.write("                            slidesToScroll: 1\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        breakpoint: 480,\r\n");
      out.write("                        settings: {\r\n");
      out.write("                            slidesToShow: 1,\r\n");
      out.write("                            slidesToScroll: 1\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                ]\r\n");
      out.write("\r\n");
      out.write("			});\r\n");
      out.write("  		})\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
