/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-20 13:50:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SignUpCondition_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SignUpCondition</title><script type=\"text/javascript\" src=\"/___vscode_livepreview_injected_script\"></script>\r\n");
      out.write("    <title>MyPageMain</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        const contextPath = \"");
      out.print( request.getContextPath() );
      out.write("\";\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"");
      out.print(contextPath );
      out.write("/assets/img/apple-icon.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(contextPath );
      out.write("/assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/assets/css/user-header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/assets/css/mypage_signup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/assets/css/templatemo.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/assets/css/fontawesome.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("   <nav class=\"navbar navbar-expand-lg navbar-light shadow main_nav_all\">\r\n");
      out.write("    <div class=\"container d-flex justify-content-between align-items-center\">\r\n");
      out.write("\r\n");
      out.write("        <a class=\"navbar-brand text-success logo h1 align-self-center\" href=\"main.html\">\r\n");
      out.write("            <img src=\"");
      out.print(contextPath );
      out.write("/assets/img/메인로고.png\" class=\"main_logo\">\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler border-0\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#templatemo_main_nav\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between\" id=\"templatemo_main_nav\">\r\n");
      out.write("            <div class=\"flex-fill\">\r\n");
      out.write("                <ul class=\"nav justify-content-end\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"LoginMain.html\">로그인</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"SignUpCondition.html\">회원가입</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"\">고객센터</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"navbar align-self-center d-flex\">\r\n");
      out.write("                <a class=\"nav-icon d-none d-lg-inline\" href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#templatemo_search\">\r\n");
      out.write("                    <i class=\"fa fa-fw fa-search text-dark mr-2\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-icon position-relative text-decoration-none\" href=\"#\">\r\n");
      out.write("                    <i class=\"fa fa-fw fa-user text-dark mr-3\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- Close Header -->\r\n");
      out.write("\r\n");
      out.write("<!-- Modal 헤드에 검색 누르면 나오는 모달  -->\r\n");
      out.write("<div class=\"modal fade bg-white\" id=\"templatemo_search\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("        <div class=\"w-100 pt-1 mb-5 text-right\">\r\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"\" method=\"get\" class=\"modal-content modal-body border-0 p-0\">\r\n");
      out.write("            <div class=\"input-group mb-2\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"inputModalSearch\" name=\"q\" placeholder=\"Search ...\">\r\n");
      out.write("                <button type=\"submit\" class=\"input-group-text bg-success text-light\">\r\n");
      out.write("                    <i class=\"fa fa-fw fa-search text-white\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <!-- start body -->\r\n");
      out.write("    <div class=\"user-login-wrapper\">\r\n");
      out.write("      <div class=\"user-login-container\">\r\n");
      out.write("        <!-- 회원가입 상단 바 시작 -->\r\n");
      out.write("        <ul class=\"nav justify-content-center\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" aria-current=\"page\" href=\"#\" > <span style=\"color:gray; font-size: 12px;\">________________________　　　쉽고 간단한 로그인 및 회원 가입　　　________________________</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"user-login-chapter\">\r\n");
      out.write("          <span class=\"user-login-chap1\">\r\n");
      out.write("           1\r\n");
      out.write("          </span>\r\n");
      out.write("          <span style=\"color: gray; font-size: 15px;\">ㅡ</span>\r\n");
      out.write("          <span class=\"user-login-chap2\">\r\n");
      out.write("            2\r\n");
      out.write("          </span>\r\n");
      out.write("          <span style=\"color: gray; font-size: 15px;\">ㅡ</span>\r\n");
      out.write("          <span class=\"user-login-chap3\">\r\n");
      out.write("            3\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <h5 style=\"margin-top: 15px;\">회원가입 약관 동의하기</h5>\r\n");
      out.write("        <!-- 회원가입 상단 바 끝 -->\r\n");
      out.write("\r\n");
      out.write("        <!-- 회원가입 폼 시작-->\r\n");
      out.write("        <div class=\"user-login-condition-wapper\">\r\n");
      out.write("      \r\n");
      out.write("          <div class=\"user-login-title-wapper\">\r\n");
      out.write("            <span class=\"user-login-condition-title\">홈페이지 약관 동의</span>\r\n");
      out.write("            <span class=\"user-login-condition-must\">(필수)</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 약관 문구 시작-->\r\n");
      out.write("          <div class=\"user-login-condition-contents\">\r\n");
      out.write("            <p style=\"font-weight: 600; font-size: 17px !important;\"> 타임포메이커는 고객님을 보호합니다.</p>\r\n");
      out.write("            <p style=\"font-size: 14px;\">본 약관은 타임포메이커 홈페이지 서비스 이용과 관련하여<br>\r\n");
      out.write("              필요한 사항을 규정합니다.</p>\r\n");
      out.write("            <p style=\"font-weight: 600; font-size: 17px;\">제 1장 총칙</p>\r\n");
      out.write("            <pre style=\" font-size: 14px;\">제 1조 (목적)\r\n");
      out.write("본 약관은 타임포메이커(이하 '회사'라 합니다)가 \r\n");
      out.write("운영하는 홈페이지(이하 '사이트'라 합니다)를 통해 \r\n");
      out.write("제공하는 모든 서비스에 대하여 회원과 회사의 권리, \r\n");
      out.write("의무, 책임 및 기타 필요한 사항을 규정함을 목적으로 합니다.\r\n");
      out.write("\r\n");
      out.write("제 2조 (약관의 효력 및 변경)\r\n");
      out.write("본 약관은 회원이 가입 시 동의함으로써 효력이 발생합니다.\r\n");
      out.write("회사는 필요한 경우 본 약관을 변경할 수 있으며, \r\n");
      out.write("변경된 약관은 사이트를 통해 공지합니다.\r\n");
      out.write("변경된 약관은 공지 즉시 효력이 발생되며, \r\n");
      out.write("회원은 변경된 약관에 대해 동의하지 않을 경우 회원탈퇴를 \r\n");
      out.write("선택할 수 있습니다. 변경된 약관에 동의하거나 \r\n");
      out.write("이용 계속으로 본 약관의 효력을 인정하는 것으로 간주됩니다.\r\n");
      out.write("            </pre>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 약관 문구 끝-->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"user-login-title-wapper\">\r\n");
      out.write("            <span class=\"user-login-condition-title\">개인정보 약관 동의</span>\r\n");
      out.write("            <span class=\"user-login-condition-must\">(필수)</span>\r\n");
      out.write("          </div>\r\n");
      out.write("           <!-- 약관 문구 시작-->\r\n");
      out.write("          <div class=\"user-login-condition-contents\">\r\n");
      out.write("            <p style=\"font-weight: 600; font-size: 17px;\" >제 1장 총칙</p>\r\n");
      out.write("              <p style=\"font-size: 14px;\">제 1조 (개인정보의 처리 목적)</p>\r\n");
      out.write("            <p style=\"font-weight: 600; font-size: 17px;\">개인정보 처리방침</p>\r\n");
      out.write("            <pre style=\"font-size: 14px;\">\r\n");
      out.write("제 1조 (개인정보의 처리 목적)\r\n");
      out.write("\r\n");
      out.write("회사는 회원들의 개인정보를 다음의 목적으로 처리합니다.\r\n");
      out.write("가. 회원가입 및 서비스 제공을 위한 계약 이행\r\n");
      out.write("나. 서비스 제공 및 운영, 관리, 개선을 위한 목적\r\n");
      out.write("다. 서비스 이용에 따른 본인 식별 및 인증\r\n");
      out.write("마. 서비스 이용에 따른 요금 정산 및 결제 처리\r\n");
      out.write("바. 서비스 이용에 따른 통계 및 분석을 위한 목적\r\n");
      out.write("사. 회원의 개인정보 보호를 위한 법령 준수\r\n");
      out.write("아. 기타 회사가 정한 서비스 이용 목적에 따른 목적\r\n");
      out.write("            </pre>\r\n");
      out.write("            <!-- 약관 문구 끝-->\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("           <!-- 동의 및 버튼 시작-->\r\n");
      out.write("           <span class=\"user-loginbtn\">\r\n");
      out.write("            <button type=\"button\" class=\"user-backbtn\" onclick=\"location.href='LoginMain.jsp'\">뒤로</button>\r\n");
      out.write("            <button type=\"submit\" class=\"user-gobtn\" onclick=\"location.href='SignUpUserInfo.jsp'\">동의</button>\r\n");
      out.write("          </span>\r\n");
      out.write("           <!-- 동의 및 버튼 끝-->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("         <!-- 회원가입 폼 끝-->\r\n");
      out.write("          \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- close body -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Start Footer -->\r\n");
      out.write("      <footer class=\"main_footer\" id=\"tempaltemo_footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <img src=\"");
      out.print(contextPath );
      out.write("/assets/img/메인로고.png\" class=\"main_logo\">\r\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fas fa-map-marker-alt fa-fw\"></i>\r\n");
      out.write("                            서울특별시 강남구 테헤란로14길6\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fa fa-phone fa-fw\"></i>\r\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fa fa-envelope fa-fw\"></i>\r\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"mailto:info@company.com\">info@company.com</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"w-100 py-3\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row pt-2\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <p class=\"text-left\">\r\n");
      out.write("                            &copy; 2023 떡잎방범대 박수진 박지현 이아인 임재린 황슬기\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Start Script -->\r\n");
      out.write("  <script src=\"");
      out.print(contextPath );
      out.write("/assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(contextPath );
      out.write("/assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(contextPath );
      out.write("/assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(contextPath );
      out.write("/assets/js/templatemo.js\"></script>\r\n");
      out.write("  <!-- End Script -->\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
