BEGIN
    FOR I IN 1..1000
    LOOP
        INSERT INTO BOARD
        VALUES( SEQ_BNO.NEXTVAL, 1, 10, '테스트제목' || I, '테스트내용입니다'|| I, 1, 0, SYSDATE, 'Y' );
    END LOOP;
END;
/


COMMIT;

SELECT *
FROM(
SELECT ROWNUM RNUM, A.*
FROM (SELECT
        BOARD_NO,
        CATEGORY_NAME,
        BOARD_TITLE,
        USER_ID,
        COUNT,
        CREATE_DATE
FROM BOARD B
JOIN CATEGORY USING(CATEGORY_NO)
JOIN MEMBER ON (BOARD_WRITER = USER_NO)
WHERE BOARD_TYPE = 1
    AND B.STATUS = 'Y'
ORDER BY BOARD_NO DESC) A
    )
WHERE RNUM BETWEEN ? AND ?;
