--1 
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

--2
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

--3
ALTER TABLE TB_CATEGORY
ADD PRIMARY KEY(NAME);

--4
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL;

--5
ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10)
MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

--6
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CATEGORY
RENAME COLUMN USE_YN TO CATEGORY_USE_YN;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;

--7
ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT SYS_C007271 TO PK_CLASS_TYPE_NAME;
ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT SYS_C007272 TO PK_CATEGORY_NAME;

--8
INSERT INTO TB_CATEGORY VALUES('공학','Y');
INSERT INTO TB_CATEGORY VALUES('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES('의학','Y');
INSERT INTO TB_CATEGORY VALUES('예체능','Y');
INSERT INTO TB_CATEGORY VALUES('인문사회','Y');
COMMIT;

--9
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTNEMT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY;

-- 관리자 계정에서 워크북 계정에 뷰를 사용할 수 있도록 권한 부여
GRANT CREATE VIEW TO WORKBOOK;

-- 뷰로 가상테이블 생성 (테이블에는 생성안됨)
CREATE VIEW VW_테스트(학번, 학생이름)
AS SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT;
SELECT * FROM VW_테스트;

-- 10 
CREATE VIEW VW_학생일반정보(학번, 학생이름, 주소)
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT;

-- 11
CREATE OR REPLACE VIEW VW_지도면담 (학생이름, 학과이름, 지도교수이름)
AS SELECT STUDENT_NAME,DEPARTMENT_NAME, NVL(PROFESSOR_NAME,'지도교수없음')
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
ORDER BY 2;

SELECT * FROM VW_지도면담;

-- 12
CREATE OR REPLACE VIEW VW_학과별학생수 (DEPARTMENT_NAME,STUDENT_COUNT)
AS SELECT DEPARTMENT_NAME, COUNT(STUDENT_NO)
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME, DEPARTMENT_NO;

SELECT * FROM VW_학과별학생수;

-- 13
UPDATE VW_학생일반정보 SET 학생이름 = '이아인' WHERE 학번 = 'A213046';

SELECT * FROM VW_학생일반정보;

-- 14
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WITH READ ONLY;

UPDATE VW_학생일반정보 SET STUDENT_NAME = '최미선' WHERE STUDENT_NO = 'A213046';
--cannot perform a DML operation on a read-only view
-- 확인 구문  read-only view를 걸어서 수정할 수 없다.

-- 15 3년(X) 5년(O)
SELECT C.CLASS_NO "과목번호", C.CLASS_NAME "과목이름", COUNT(G.STUDENT_NO) "누적수강생수(명)"
FROM TB_CLASS C
JOIN TB_GRADE G USING (CLASS_NO);














